apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-service
  description: A simple Node.js service example
  annotations:
    github.com/project-slug: 'anuragpachauri/test-service'
    backstage.io/kubernetes-id: 'kind-backstage'
    argocd/app-name: 'test-app'
    jira.com/project-key: 'BL'
    statuspage.io/components: instance:x6qwhglp64qj,7l83zp7d4yk7,20h4dcgndfkn,2hv6z1ngbl19,c9fq2sv62c73
    datadoghq.com/site: https://p.us5.datadoghq.com/sb/85cfa16b-6394-11ef-b68e-a2c6e293d47f-61db6e11810709df35962b3e8c9b6415
spec:
  type: service
  lifecycle: experimental
  owner: backstage
